### ISSUE TITLE
Docker build failiing for this model

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos7kpb#26]

**Comment by DhanshreeA** [comment]
Docker build currently failing because it needs glibc

**Comment by DhanshreeA** [comment]
Relevant snippet from the logs:

```bash
2024-02-22T11:01:07.1631222Z #9 158.7 11:01:07 | ERROR    | Ersilia exception class:
2024-02-22T11:01:07.1632026Z #9 158.7 EmptyOutputError
2024-02-22T11:01:07.1632502Z #9 158.7 
2024-02-22T11:01:07.1632900Z #9 158.7 Detailed error:
2024-02-22T11:01:07.1633800Z #9 158.7 Model API eos7kpb:run did not produce an outputTraceback (most recent call last):
2024-02-22T11:01:07.1635552Z #9 158.7   File "/root/eos/repository/eos7kpb/20240222110039_FD405D/eos7kpb/artifacts/framework/code/main.py", line 73, in <module>
2024-02-22T11:01:07.1636922Z #9 158.7     models = load_models()
2024-02-22T11:01:07.1638287Z #9 158.7   File "/root/eos/repository/eos7kpb/20240222110039_FD405D/eos7kpb/artifacts/framework/code/main.py", line 59, in load_models
2024-02-22T11:01:07.1639858Z #9 158.7     models[mn] = joblib.load(os.path.join(models_dir, fn))
2024-02-22T11:01:07.1641646Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
2024-02-22T11:01:07.1642940Z #9 158.7     obj = _unpickle(fobj, filename, mmap_mode)
2024-02-22T11:01:07.1644434Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
2024-02-22T11:01:07.1645699Z #9 158.7     obj = unpickler.load()
2024-02-22T11:01:07.1646539Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/pickle.py", line 1212, in load
2024-02-22T11:01:07.1647414Z #9 158.7     dispatch[key[0]](self)
2024-02-22T11:01:07.1648447Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/pickle.py", line 1537, in load_stack_global
2024-02-22T11:01:07.1649599Z #9 158.7     self.append(self.find_class(module, name))
2024-02-22T11:01:07.1651383Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/pickle.py", line 1579, in find_class
2024-02-22T11:01:07.1652440Z #9 158.7     __import__(module, level=0)
2024-02-22T11:01:07.1653823Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/__init__.py", line 2, in <module>
2024-02-22T11:01:07.1655181Z #9 158.7     from flaml.automl import AutoML, logger_formatter
2024-02-22T11:01:07.1656812Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/automl/__init__.py", line 1, in <module>
2024-02-22T11:01:07.1658209Z #9 158.7     from flaml.automl.automl import AutoML, size
2024-02-22T11:01:07.1659745Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/automl/automl.py", line 15, in <module>
2024-02-22T11:01:07.1661190Z #9 158.7     from flaml.automl.state import SearchState, AutoMLState
2024-02-22T11:01:07.1662819Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/automl/state.py", line 8, in <module>
2024-02-22T11:01:07.1664540Z #9 158.7     from flaml.automl.ml import compute_estimator, train_estimator
2024-02-22T11:01:07.1666188Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/automl/ml.py", line 14, in <module>
2024-02-22T11:01:07.1667711Z #9 158.7     from flaml.automl.model import BaseEstimator, TransformersEstimator
2024-02-22T11:01:07.1669463Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/flaml/automl/model.py", line 65, in <module>
2024-02-22T11:01:07.1670962Z #9 158.7     from lightgbm import LGBMClassifier, LGBMRegressor, LGBMRanker
2024-02-22T11:01:07.1672613Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
2024-02-22T11:01:07.1674081Z #9 158.7     from .basic import Booster, Dataset, Sequence, register_logger
2024-02-22T11:01:07.1675708Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/lightgbm/basic.py", line 110, in <module>
2024-02-22T11:01:07.1676987Z #9 158.7     _LIB = _load_lib()
2024-02-22T11:01:07.1678338Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/lightgbm/basic.py", line 101, in _load_lib
2024-02-22T11:01:07.1679682Z #9 158.7     lib = ctypes.cdll.LoadLibrary(lib_path[0])
2024-02-22T11:01:07.1681238Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
2024-02-22T11:01:07.1682623Z #9 158.7     return self._dlltype(name)
2024-02-22T11:01:07.1683708Z #9 158.7   File "/usr/bin/conda/envs/eos7kpb/lib/python3.9/ctypes/__init__.py", line 382, in __init__
2024-02-22T11:01:07.1684878Z #9 158.7     self._handle = _dlopen(self._name, mode)
2024-02-22T11:01:07.1686991Z #9 158.7 OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/bin/conda/envs/eos7kpb/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so)
2024-02-22T11:01:07.1688735Z #9 158.7 
2024-02-22T11:01:07.1689101Z #9 158.7 
```
